# coding: utf-8

"""
    Orchestra API

    Code Version 1.0.7.15

    The version of the OpenAPI document: Prod
    Generated by: https://konfigthis.com
"""

import unittest

import os
from pprint import pprint
from blue_time_python_sdk import BlueTime

class TestSimple(unittest.TestCase):
    def setUp(self):
        pass

    def test_client(self):
        bluetime = BlueTime(
        
                        api_key_auth = 'YOUR_API_KEY',
        
            access_token = 'YOUR_BEARER_TOKEN'
        )
        self.assertIsNotNone(bluetime)

    def tearDown(self):
        pass


if __name__ == "__main__":
    unittest.main()
