# coding: utf-8
"""
    Orchestra API

    Code Version 1.0.7.15

    The version of the OpenAPI document: Prod
    Generated by: https://konfigthis.com
"""

import typing
import inspect
from datetime import date, datetime
from blue_time_python_sdk.client_custom import ClientCustom
from blue_time_python_sdk.configuration import Configuration
from blue_time_python_sdk.api_client import ApiClient
from blue_time_python_sdk.type_util import copy_signature
from blue_time_python_sdk.apis.tags.card_operations_api import CardOperationsApi
from blue_time_python_sdk.apis.tags.custom_forms_api import CustomFormsApi
from blue_time_python_sdk.apis.tags.cvv_operations_api import CvvOperationsApi
from blue_time_python_sdk.apis.tags.network_token_api import NetworkTokenApi
from blue_time_python_sdk.apis.tags.payment_gateway_api import PaymentGatewayApi
from blue_time_python_sdk.apis.tags.payment_gateway_accounts_api import PaymentGatewayAccountsApi
from blue_time_python_sdk.apis.tags.string_tokens_api import StringTokensApi
from blue_time_python_sdk.apis.tags.three_ds_merchants_api import ThreeDsMerchantsApi
from blue_time_python_sdk.apis.tags.three_ds_sessions_api import ThreeDsSessionsApi
from blue_time_python_sdk.apis.tags.tools_api import ToolsApi
from blue_time_python_sdk.apis.tags.utils_api import UtilsApi



class BlueTime(ClientCustom):

    def __init__(self, configuration: typing.Union[Configuration, None] = None, **kwargs):
        super().__init__(configuration, **kwargs)
        if (len(kwargs) > 0):
            configuration = Configuration(**kwargs)
        if (configuration is None):
            raise Exception("configuration is required")
        api_client = ApiClient(configuration)
        self.card_operations: CardOperationsApi = CardOperationsApi(api_client)
        self.custom_forms: CustomFormsApi = CustomFormsApi(api_client)
        self.cvv_operations: CvvOperationsApi = CvvOperationsApi(api_client)
        self.network_token: NetworkTokenApi = NetworkTokenApi(api_client)
        self.payment_gateway: PaymentGatewayApi = PaymentGatewayApi(api_client)
        self.payment_gateway_accounts: PaymentGatewayAccountsApi = PaymentGatewayAccountsApi(api_client)
        self.string_tokens: StringTokensApi = StringTokensApi(api_client)
        self.three_ds_merchants: ThreeDsMerchantsApi = ThreeDsMerchantsApi(api_client)
        self.three_ds_sessions: ThreeDsSessionsApi = ThreeDsSessionsApi(api_client)
        self.tools: ToolsApi = ToolsApi(api_client)
        self.utils: UtilsApi = UtilsApi(api_client)
