# coding: utf-8

"""
    Orchestra API

    Code Version 1.0.7.15

    The version of the OpenAPI document: Prod
    Generated by: https://konfigthis.com
"""

import unittest

import blue_time_python_sdk
from blue_time_python_sdk.model.custom_forms_upload_form_folder_request_headers import CustomFormsUploadFormFolderRequestHeaders
from blue_time_python_sdk import configuration


class TestCustomFormsUploadFormFolderRequestHeaders(unittest.TestCase):
    """CustomFormsUploadFormFolderRequestHeaders unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
