# coding: utf-8

"""
    Orchestra API

    Code Version 1.0.7.15

    The version of the OpenAPI document: Prod
    Generated by: https://konfigthis.com
"""

import unittest

import blue_time_python_sdk
from blue_time_python_sdk.model.three_ds_merchants_list_merchants_response import ThreeDsMerchantsListMerchantsResponse
from blue_time_python_sdk import configuration


class TestThreeDsMerchantsListMerchantsResponse(unittest.TestCase):
    """ThreeDsMerchantsListMerchantsResponse unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
