# coding: utf-8

"""
    Orchestra API

    Code Version 1.0.7.15

    The version of the OpenAPI document: Prod
    Generated by: https://konfigthis.com
"""

import unittest

import blue_time_python_sdk
from blue_time_python_sdk.model.pay_tools_api_models_card_ops_charge_request import PayToolsApiModelsCardOpsChargeRequest
from blue_time_python_sdk import configuration


class TestPayToolsApiModelsCardOpsChargeRequest(unittest.TestCase):
    """PayToolsApiModelsCardOpsChargeRequest unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
