# coding: utf-8

"""
    Orchestra API

    Code Version 1.0.7.15

    The version of the OpenAPI document: Prod
    Generated by: https://konfigthis.com
"""

import unittest

import blue_time_python_sdk
from blue_time_python_sdk.model.pay_tools_shared_models_card_stored_card import PayToolsSharedModelsCardStoredCard
from blue_time_python_sdk import configuration


class TestPayToolsSharedModelsCardStoredCard(unittest.TestCase):
    """PayToolsSharedModelsCardStoredCard unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
