# coding: utf-8

"""
    Orchestra API

    Code Version 1.0.7.15

    The version of the OpenAPI document: Prod
    Generated by: https://konfigthis.com
"""

import unittest

import blue_time_python_sdk
from blue_time_python_sdk.model.pay_tools_dal_entities_three_ds_merchant import PayToolsDalEntitiesThreeDsMerchant
from blue_time_python_sdk import configuration


class TestPayToolsDalEntitiesThreeDsMerchant(unittest.TestCase):
    """PayToolsDalEntitiesThreeDsMerchant unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
