# coding: utf-8

"""
    Orchestra API

    Code Version 1.0.7.15

    The version of the OpenAPI document: Prod
    Generated by: https://konfigthis.com
"""

import unittest

import blue_time_python_sdk
from blue_time_python_sdk.model.custom_forms_remove_form_response import CustomFormsRemoveFormResponse
from blue_time_python_sdk import configuration


class TestCustomFormsRemoveFormResponse(unittest.TestCase):
    """CustomFormsRemoveFormResponse unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
