# coding: utf-8

"""
    Orchestra API

    Code Version 1.0.7.15

    The version of the OpenAPI document: Prod
    Generated by: https://konfigthis.com
"""

import unittest

import blue_time_python_sdk
from blue_time_python_sdk.model.payments_currency_code import PaymentsCurrencyCode
from blue_time_python_sdk import configuration


class TestPaymentsCurrencyCode(unittest.TestCase):
    """PaymentsCurrencyCode unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
