# coding: utf-8

"""
    Orchestra API

    Code Version 1.0.7.15

    The version of the OpenAPI document: Prod
    Generated by: https://konfigthis.com
"""

import unittest

import blue_time_python_sdk
from blue_time_python_sdk.model.payment_gateway_accounts_get_all_response import PaymentGatewayAccountsGetAllResponse
from blue_time_python_sdk import configuration


class TestPaymentGatewayAccountsGetAllResponse(unittest.TestCase):
    """PaymentGatewayAccountsGetAllResponse unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
