# coding: utf-8

"""
    Orchestra API

    Code Version 1.0.7.15

    The version of the OpenAPI document: Prod
    Generated by: https://konfigthis.com
"""

from blue_time_python_sdk.paths.custom_forms.get import GetList
from blue_time_python_sdk.paths.custom_forms_name.delete import RemoveForm
from blue_time_python_sdk.paths.custom_forms_name.put import UploadFormFolder
from blue_time_python_sdk.apis.tags.custom_forms_api_raw import CustomFormsApiRaw


class CustomFormsApi(
    GetList,
    RemoveForm,
    UploadFormFolder,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: CustomFormsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = CustomFormsApiRaw(api_client)
