# coding: utf-8

"""
    Orchestra API

    Code Version 1.0.7.15

    The version of the OpenAPI document: Prod
    Generated by: https://konfigthis.com
"""

from blue_time_python_sdk.paths.cvv_operations.post import GetTokenCvvOperation
from blue_time_python_sdk.paths.cvv_operations_charge.post import PerformUniversalPaymentGatewayCharge
from blue_time_python_sdk.paths.cvv_operations_op_validate.get import ValidateOperation
from blue_time_python_sdk.apis.tags.cvv_operations_api_raw import CvvOperationsApiRaw


class CvvOperationsApi(
    GetTokenCvvOperation,
    PerformUniversalPaymentGatewayCharge,
    ValidateOperation,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: CvvOperationsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = CvvOperationsApiRaw(api_client)
