# coding: utf-8

"""
    Orchestra API

    Code Version 1.0.7.15

    The version of the OpenAPI document: Prod
    Generated by: https://konfigthis.com
"""

from blue_time_python_sdk.paths.network_token.post import CardTokenizeRaw
from blue_time_python_sdk.paths.network_token.delete import DeleteRaw


class NetworkTokenApiRaw(
    CardTokenizeRaw,
    DeleteRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
