# coding: utf-8

"""
    Orchestra API

    Code Version 1.0.7.15

    The version of the OpenAPI document: Prod
    Generated by: https://konfigthis.com
"""

from blue_time_python_sdk.paths.network_token.post import CardTokenize
from blue_time_python_sdk.paths.network_token.delete import Delete
from blue_time_python_sdk.apis.tags.network_token_api_raw import NetworkTokenApiRaw


class NetworkTokenApi(
    CardTokenize,
    Delete,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: NetworkTokenApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = NetworkTokenApiRaw(api_client)
