# coding: utf-8

"""
    Orchestra API

    Code Version 1.0.7.15

    The version of the OpenAPI document: Prod
    Generated by: https://konfigthis.com
"""

from blue_time_python_sdk.paths.payment_gateway.get import ListGateways
from blue_time_python_sdk.paths.payment_gateway_authorize.post import PerformAuthorizeOperation
from blue_time_python_sdk.paths.payment_gateway_capture.put import PerformCaptureOperation
from blue_time_python_sdk.paths.payment_gateway_charge.post import PerformChargeOperation
from blue_time_python_sdk.paths.payment_gateway_refund.put import PerformRefundOperation
from blue_time_python_sdk.paths.payment_gateway_void.delete import VoidOperation
from blue_time_python_sdk.apis.tags.payment_gateway_api_raw import PaymentGatewayApiRaw


class PaymentGatewayApi(
    ListGateways,
    PerformAuthorizeOperation,
    PerformCaptureOperation,
    PerformChargeOperation,
    PerformRefundOperation,
    VoidOperation,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: PaymentGatewayApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = PaymentGatewayApiRaw(api_client)
