# coding: utf-8

"""
    Orchestra API

    Code Version 1.0.7.15

    The version of the OpenAPI document: Prod
    Generated by: https://konfigthis.com
"""

from blue_time_python_sdk.paths.string_tokens_token.delete import DeleteByToken
from blue_time_python_sdk.paths.string_tokens_token.get import GetContent
from blue_time_python_sdk.paths.string_tokens_token_meta.get import GetMetaData
from blue_time_python_sdk.paths.string_tokens.post import StoreAndTokenize
from blue_time_python_sdk.apis.tags.string_tokens_api_raw import StringTokensApiRaw


class StringTokensApi(
    DeleteByToken,
    GetContent,
    GetMetaData,
    StoreAndTokenize,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: StringTokensApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = StringTokensApiRaw(api_client)
