# coding: utf-8

"""
    Orchestra API

    Code Version 1.0.7.15

    The version of the OpenAPI document: Prod
    Generated by: https://konfigthis.com
"""

from blue_time_python_sdk.paths.string_tokens_token.delete import DeleteByTokenRaw
from blue_time_python_sdk.paths.string_tokens_token.get import GetContentRaw
from blue_time_python_sdk.paths.string_tokens_token_meta.get import GetMetaDataRaw
from blue_time_python_sdk.paths.string_tokens.post import StoreAndTokenizeRaw


class StringTokensApiRaw(
    DeleteByTokenRaw,
    GetContentRaw,
    GetMetaDataRaw,
    StoreAndTokenizeRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
