# coding: utf-8

"""
    Orchestra API

    Code Version 1.0.7.15

    The version of the OpenAPI document: Prod
    Generated by: https://konfigthis.com
"""

from blue_time_python_sdk.paths.three_ds_merchants_name.get import GetMerchantInfo
from blue_time_python_sdk.paths.three_ds_merchants.get import ListMerchants
from blue_time_python_sdk.paths.three_ds_merchants_name.delete import RemoveMerchant
from blue_time_python_sdk.paths.three_ds_merchants_name.put import UpdateMerchantInfo
from blue_time_python_sdk.apis.tags.three_ds_merchants_api_raw import ThreeDsMerchantsApiRaw


class ThreeDsMerchantsApi(
    GetMerchantInfo,
    ListMerchants,
    RemoveMerchant,
    UpdateMerchantInfo,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: ThreeDsMerchantsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = ThreeDsMerchantsApiRaw(api_client)
