# coding: utf-8

"""
    Orchestra API

    Code Version 1.0.7.15

    The version of the OpenAPI document: Prod
    Generated by: https://konfigthis.com
"""

from blue_time_python_sdk.paths.three_ds_sessions_challenge_status.get import GetChallengeStatus
from blue_time_python_sdk.paths.three_ds_sessions.post import GetTokenStartOperation
from blue_time_python_sdk.paths.three_ds_sessions_fingerprint_callback_session_id.post import HandleFingerprintCallback
from blue_time_python_sdk.paths.three_ds_sessions_mpi_challenge_callback_session_id.get import HandleMpiChallengeCallback
from blue_time_python_sdk.paths.three_ds_sessions_op_validate.get import PerformValidationOperation
from blue_time_python_sdk.apis.tags.three_ds_sessions_api_raw import ThreeDsSessionsApiRaw


class ThreeDsSessionsApi(
    GetChallengeStatus,
    GetTokenStartOperation,
    HandleFingerprintCallback,
    HandleMpiChallengeCallback,
    PerformValidationOperation,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: ThreeDsSessionsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = ThreeDsSessionsApiRaw(api_client)
