# coding: utf-8

"""
    Orchestra API

    Code Version 1.0.7.15

    The version of the OpenAPI document: Prod
    Generated by: https://konfigthis.com
"""

from blue_time_python_sdk.paths.tools_brand.get import GetBrandLookupRaw
from blue_time_python_sdk.paths.tools_iin.get import LookupMetadataRaw
from blue_time_python_sdk.paths.tools_validate.post import ValidateCardDetailsRaw
from blue_time_python_sdk.paths.tools_luhn.get import ValidateLuhnCardRaw


class ToolsApiRaw(
    GetBrandLookupRaw,
    LookupMetadataRaw,
    ValidateCardDetailsRaw,
    ValidateLuhnCardRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
