# coding: utf-8

"""
    Orchestra API

    Code Version 1.0.7.15

    The version of the OpenAPI document: Prod
    Generated by: https://konfigthis.com
"""

from blue_time_python_sdk.paths.utils_api_key.get import ValidateApiKey
from blue_time_python_sdk.apis.tags.utils_api_raw import UtilsApiRaw


class UtilsApi(
    ValidateApiKey,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: UtilsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = UtilsApiRaw(api_client)
