# coding: utf-8

"""
    Orchestra API

    Code Version 1.0.7.15

    The version of the OpenAPI document: Prod
    Generated by: https://konfigthis.com
"""

import unittest
from unittest.mock import patch

import urllib3

import blue_time_python_sdk
from blue_time_python_sdk.paths.card_operations_op_validate import get
from blue_time_python_sdk import configuration, schemas, api_client

from .. import ApiTestMixin


class TestCardOperationsOpValidate(ApiTestMixin, unittest.TestCase):
    """
    CardOperationsOpValidate unit test stubs
        Perform validation of the operation using to signed data
    """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    response_status = 200




if __name__ == '__main__':
    unittest.main()
