# coding: utf-8

"""
    Orchestra API

    Code Version 1.0.7.15

    The version of the OpenAPI document: Prod
    Generated by: https://konfigthis.com
"""

import unittest
from unittest.mock import patch

import urllib3

import blue_time_python_sdk
from blue_time_python_sdk.paths.three_ds_sessions_challenge_status import get
from blue_time_python_sdk import configuration, schemas, api_client

from .. import ApiTestMixin


class TestThreeDsSessionsChallengeStatus(ApiTestMixin, unittest.TestCase):
    """
    ThreeDsSessionsChallengeStatus unit test stubs
        Get challenge ststus, as stored on server
    """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    response_status = 200




if __name__ == '__main__':
    unittest.main()
