# coding: utf-8

"""
    Orchestra API

    Code Version 1.0.7.15

    The version of the OpenAPI document: Prod
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from blue_time_python_sdk.type.custom_forms_upload_form_folder_request1_headers import CustomFormsUploadFormFolderRequest1Headers

class RequiredCustomFormsUploadFormFolderRequest1(TypedDict):
    pass

class OptionalCustomFormsUploadFormFolderRequest1(TypedDict, total=False):
    ContentType: str

    ContentDisposition: str

    Headers: CustomFormsUploadFormFolderRequest1Headers

    Length: int

    Name: str

    FileName: str

class CustomFormsUploadFormFolderRequest1(RequiredCustomFormsUploadFormFolderRequest1, OptionalCustomFormsUploadFormFolderRequest1):
    pass
