# coding: utf-8

"""
    Orchestra API

    Code Version 1.0.7.15

    The version of the OpenAPI document: Prod
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredPayToolsApiModelsThreeDSAuthenticationInputModel(TypedDict):
    # 3ds Version
    version: str

    # Authentication value
    authenticationValue: str

    # Electronic Commerce Indicator
    eci: str

    # transaction ID from the 3D Secure provider
    xid: str

    # Merchant name
    merchantName: str

class OptionalPayToolsApiModelsThreeDSAuthenticationInputModel(TypedDict, total=False):
    pass

class PayToolsApiModelsThreeDSAuthenticationInputModel(RequiredPayToolsApiModelsThreeDSAuthenticationInputModel, OptionalPayToolsApiModelsThreeDSAuthenticationInputModel):
    pass
