# coding: utf-8

"""
    Orchestra API

    Code Version 1.0.7.15

    The version of the OpenAPI document: Prod
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from blue_time_python_sdk.type.payments_card_types import PaymentsCardTypes

class RequiredPayToolsBlAuthenticationThreeDsBrand(TypedDict):
    # Brand's Bin
    bin: str

    # Merchant Id
    mid: str

    # Brand's MCC
    mcc: str

class OptionalPayToolsBlAuthenticationThreeDsBrand(TypedDict, total=False):
    brd: PaymentsCardTypes

class PayToolsBlAuthenticationThreeDsBrand(RequiredPayToolsBlAuthenticationThreeDsBrand, OptionalPayToolsBlAuthenticationThreeDsBrand):
    pass
