# coding: utf-8

"""
    Orchestra API

    Code Version 1.0.7.15

    The version of the OpenAPI document: Prod
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from blue_time_python_sdk.type.pay_tools_api_models_three_ds_authentication_input_model import PayToolsApiModelsThreeDSAuthenticationInputModel
from blue_time_python_sdk.type.payments_card_types import PaymentsCardTypes

class RequiredPayToolsApiModelsCardInputModel(TypedDict):
    # Cardholder name (as apears on card)
    cardHolderName: str

    # Card number (PAN) or a Reference to a Tokenized string. A Token should be referenced in the format @TOKEN, e.g \"@nQGywsQE9gbURtrXEjTZwtWqeMdK9nsO\"
    cardNumber: str

    # Expiration year
    expirationYear: int

    # Expiration month
    expirationMonth: int

class OptionalPayToolsApiModelsCardInputModel(TypedDict, total=False):
    # Card owner Id
    ownerID: typing.Optional[str]

    # Card Issue Number
    issueNumber: typing.Optional[str]

    # Card security code (digits on back of card)
    cvv: typing.Optional[str]

    threeDSAuthentication: PayToolsApiModelsThreeDSAuthenticationInputModel

    cardType: PaymentsCardTypes

class PayToolsApiModelsCardInputModel(RequiredPayToolsApiModelsCardInputModel, OptionalPayToolsApiModelsCardInputModel):
    pass
