# coding: utf-8

"""
    Orchestra API

    Code Version 1.0.7.15

    The version of the OpenAPI document: Prod
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredPayToolsApiModelsJwsMultipleOutputModel(TypedDict):
    pass

class OptionalPayToolsApiModelsJwsMultipleOutputModel(TypedDict, total=False):
    # The jws (token) value to be used for 3DS
    threeDsAuthToken: typing.Optional[str]

    # The jws (token) value to be used in subsequent card operation methods
    authToken: typing.Optional[str]

class PayToolsApiModelsJwsMultipleOutputModel(RequiredPayToolsApiModelsJwsMultipleOutputModel, OptionalPayToolsApiModelsJwsMultipleOutputModel):
    pass
