# coding: utf-8

"""
    Orchestra API

    Code Version 1.0.7.15

    The version of the OpenAPI document: Prod
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from blue_time_python_sdk.type.pay_tools_bl_authentication_three_ds_brand import PayToolsBlAuthenticationThreeDsBrand

class RequiredPayToolsBlAuthenticationThreeDMerchant(TypedDict):
    # Merchant name
    mnm: str

    # Merchant's display name
    mds: str

    # Merchant's Requestor Id suffix
    msf: str

    # Merchant's Country (3-digit ISO 3166-1 numeric)
    cnt: str

    # Merchant's Url
    url: str

    # List of supported brands
    brds: typing.List[PayToolsBlAuthenticationThreeDsBrand]

class OptionalPayToolsBlAuthenticationThreeDMerchant(TypedDict, total=False):
    pass

class PayToolsBlAuthenticationThreeDMerchant(RequiredPayToolsBlAuthenticationThreeDMerchant, OptionalPayToolsBlAuthenticationThreeDMerchant):
    pass
