# coding: utf-8

"""
    Orchestra API

    Code Version 1.0.7.15

    The version of the OpenAPI document: Prod
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from blue_time_python_sdk.type.pay_tools_bl_authentication_charge_preset_data import PayToolsBlAuthenticationChargePresetData
from blue_time_python_sdk.type.pay_tools_bl_authentication_three_ds_preset_data import PayToolsBlAuthenticationThreeDsPresetData
from blue_time_python_sdk.type.pay_tools_bl_authentication_tokenization_action import PayToolsBlAuthenticationTokenizationAction
from blue_time_python_sdk.type.pay_tools_shared_enums_perform3ds import PayToolsSharedEnumsPerform3ds
from blue_time_python_sdk.type.payments_charge_request import PaymentsChargeRequest
from blue_time_python_sdk.type.payments_operation_result import PaymentsOperationResult
from blue_time_python_sdk.type.pci_booking_iin_lookup_library_card_validation_request import PciBookingIINLookupLibraryCardValidationRequest
from blue_time_python_sdk.type.pci_booking_iin_lookup_library_card_validation_result import PciBookingIINLookupLibraryCardValidationResult
from blue_time_python_sdk.type.pci_booking_iin_lookup_library_risk_level import PciBookingIINLookupLibraryRiskLevel

RequiredPayToolsBlAuthenticationSignedData = TypedDict("RequiredPayToolsBlAuthenticationSignedData", {
    })

OptionalPayToolsBlAuthenticationSignedData = TypedDict("OptionalPayToolsBlAuthenticationSignedData", {
    "vld_rq": PciBookingIINLookupLibraryCardValidationRequest,

    "vld_rs": PciBookingIINLookupLibraryCardValidationResult,

    "crg_rq": PaymentsChargeRequest,

    "crg_rs": PaymentsOperationResult,

    # Result from tokenization
    "tkn_rs": typing.Optional[str],

    "3ds_d": PayToolsBlAuthenticationThreeDsPresetData,

    "vld": PciBookingIINLookupLibraryRiskLevel,

    "3ds": PayToolsSharedEnumsPerform3ds,

    # Is Card charge required for this session
    "crg": bool,

    "tkn": PayToolsBlAuthenticationTokenizationAction,

    "crg_d": PayToolsBlAuthenticationChargePresetData,
    }, total=False)

class PayToolsBlAuthenticationSignedData(RequiredPayToolsBlAuthenticationSignedData, OptionalPayToolsBlAuthenticationSignedData):
    pass
