# coding: utf-8

"""
    Orchestra API

    Code Version 1.0.7.15

    The version of the OpenAPI document: Prod
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from blue_time_python_sdk.type.network_token_request_source import NetworkTokenRequestSource
from blue_time_python_sdk.type.payments_network_token_schemes import PaymentsNetworkTokenSchemes

class RequiredPayToolsApiModelsNetworkTokenizationDeleteTokenRequest(TypedDict):
    source: NetworkTokenRequestSource

    # Token Id within the Brand
    tokenId: str

class OptionalPayToolsApiModelsNetworkTokenizationDeleteTokenRequest(TypedDict, total=False):
    brand: PaymentsNetworkTokenSchemes

    # Reason for deletion
    reason: typing.Optional[str]

class PayToolsApiModelsNetworkTokenizationDeleteTokenRequest(RequiredPayToolsApiModelsNetworkTokenizationDeleteTokenRequest, OptionalPayToolsApiModelsNetworkTokenizationDeleteTokenRequest):
    pass
