# coding: utf-8

"""
    Orchestra API

    Code Version 1.0.7.15

    The version of the OpenAPI document: Prod
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from blue_time_python_sdk.type.pay_tools_api_models_payment_gateway_description_model_credentials_names import PayToolsApiModelsPaymentGatewayDescriptionModelCredentialsNames

class RequiredPayToolsApiModelsPaymentGatewayDescriptionModel(TypedDict):
    pass

class OptionalPayToolsApiModelsPaymentGatewayDescriptionModel(TypedDict, total=False):
    # Payment Gateway Description (informational)
    description: typing.Optional[str]

    # The ePayTools internal identifier for this Payment Gateway
    name: typing.Optional[str]

    # The name of the Payment Gateway in friendly format
    displayName: typing.Optional[str]

    # Url to Payment Gateway site (informational)
    paymentGatewayUrl: typing.Optional[str]

    credentialsNames: typing.Optional[PayToolsApiModelsPaymentGatewayDescriptionModelCredentialsNames]

    # Indicates whether the Payment gateway supports Network Token (from Card schemes)
    supportsNetworkToken: bool

class PayToolsApiModelsPaymentGatewayDescriptionModel(RequiredPayToolsApiModelsPaymentGatewayDescriptionModel, OptionalPayToolsApiModelsPaymentGatewayDescriptionModel):
    pass
