# coding: utf-8

"""
    Orchestra API

    Code Version 1.0.7.15

    The version of the OpenAPI document: Prod
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredPayToolsApiModelsCardBaseWithSecurityCode(TypedDict):
    # Card number (PAN) or a Reference to a Tokenized string. A Token should be referenced in the format @TOKEN, e.g \"@nQGywsQE9gbURtrXEjTZwtWqeMdK9nsO\"
    cardNumber: str

    # Expiration year
    expirationYear: int

    # Expiration month
    expirationMonth: int

class OptionalPayToolsApiModelsCardBaseWithSecurityCode(TypedDict, total=False):
    # Card security code (digits on back of card)
    cvv: typing.Optional[str]

class PayToolsApiModelsCardBaseWithSecurityCode(RequiredPayToolsApiModelsCardBaseWithSecurityCode, OptionalPayToolsApiModelsCardBaseWithSecurityCode):
    pass
