# coding: utf-8

"""
    Orchestra API

    Code Version 1.0.7.15

    The version of the OpenAPI document: Prod
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from blue_time_python_sdk.type.pay_tools_dal_entities_three_ds_merchant import PayToolsDalEntitiesThreeDsMerchant

class RequiredPayToolsApiModelsThreeDsMerchantOutputModel(TypedDict):
    pass

class OptionalPayToolsApiModelsThreeDsMerchantOutputModel(TypedDict, total=False):
    # Account name (Name on system)
    name: typing.Optional[str]

    threeDsMerchant: PayToolsDalEntitiesThreeDsMerchant

class PayToolsApiModelsThreeDsMerchantOutputModel(RequiredPayToolsApiModelsThreeDsMerchantOutputModel, OptionalPayToolsApiModelsThreeDsMerchantOutputModel):
    pass
