# coding: utf-8

"""
    Orchestra API

    Code Version 1.0.7.15

    The version of the OpenAPI document: Prod
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredPayToolsApiModelsPayerDetails(TypedDict):
    # Client IP address
    clientIPAddress: str

    # 2 letter country code (<a href=\"https://en.wikipedia.org/wiki/ISO_3166-2#Current_codes\" target=\"_blank\">ISO 3166-2 <img src=\"https://files.readme.io/b676144-openNewWindow.png\" width=\"10\" /></a>)
    countryCode: str

class OptionalPayToolsApiModelsPayerDetails(TypedDict, total=False):
    # 1st address line
    address1: typing.Optional[str]

    # 2nd address line
    address2: typing.Optional[str]

    # 3rd address line
    address3: typing.Optional[str]

    # Postal code or Zip code
    postCode: typing.Optional[str]

    # City
    city: typing.Optional[str]

    # State or Province
    stateProvince: typing.Optional[str]

class PayToolsApiModelsPayerDetails(RequiredPayToolsApiModelsPayerDetails, OptionalPayToolsApiModelsPayerDetails):
    pass
