# coding: utf-8

"""
    Orchestra API

    Code Version 1.0.7.15

    The version of the OpenAPI document: Prod
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from blue_time_python_sdk.type.pay_tools_shared_models_money_model import PayToolsSharedModelsMoneyModel

class RequiredPayToolsBlAuthenticationChargePresetData(TypedDict):
    pass

class OptionalPayToolsBlAuthenticationChargePresetData(TypedDict, total=False):
    # Order description
    dsc: typing.Optional[str]

    # Creator reference
    ref: typing.Optional[str]

    # Is it digital goods
    dig: bool

    amt: PayToolsSharedModelsMoneyModel

    # The Upg Account name
    uan: typing.Optional[str]

    # The Upg Client Certificate name
    ucc: typing.Optional[str]

class PayToolsBlAuthenticationChargePresetData(RequiredPayToolsBlAuthenticationChargePresetData, OptionalPayToolsBlAuthenticationChargePresetData):
    pass
