# coding: utf-8

"""
    Orchestra API

    Code Version 1.0.7.15

    The version of the OpenAPI document: Prod
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from blue_time_python_sdk.type.payments_currency_code import PaymentsCurrencyCode

class RequiredPayToolsSharedModelsMoneyModel(TypedDict):
    cur: PaymentsCurrencyCode

    # Amount
    amt: typing.Union[int, float]

class OptionalPayToolsSharedModelsMoneyModel(TypedDict, total=False):
    pass

class PayToolsSharedModelsMoneyModel(RequiredPayToolsSharedModelsMoneyModel, OptionalPayToolsSharedModelsMoneyModel):
    pass
