# coding: utf-8

"""
    Orchestra API

    Code Version 1.0.7.15

    The version of the OpenAPI document: Prod
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredPayToolsApiModelsCvvOpsChargeRequest(TypedDict):
    # The card details that should be charged. You can either provide us with the raw card details or provide a reference to the stored card details in a token.
    cvv: str

class OptionalPayToolsApiModelsCvvOpsChargeRequest(TypedDict, total=False):
    pass

class PayToolsApiModelsCvvOpsChargeRequest(RequiredPayToolsApiModelsCvvOpsChargeRequest, OptionalPayToolsApiModelsCvvOpsChargeRequest):
    pass
