# coding: utf-8

"""
    Orchestra API

    Code Version 1.0.7.15

    The version of the OpenAPI document: Prod
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredPayToolsApiModelsPayerBase(TypedDict):
    # 2 letter country code (<a href=\"https://en.wikipedia.org/wiki/ISO_3166-2#Current_codes\" target=\"_blank\">ISO 3166-2 <img src=\"https://files.readme.io/b676144-openNewWindow.png\" width=\"10\" /></a>)
    countryCode: str

class OptionalPayToolsApiModelsPayerBase(TypedDict, total=False):
    # City
    city: typing.Optional[str]

    # State or Province
    stateProvince: typing.Optional[str]

class PayToolsApiModelsPayerBase(RequiredPayToolsApiModelsPayerBase, OptionalPayToolsApiModelsPayerBase):
    pass
