# coding: utf-8

"""
    Orchestra API

    Code Version 1.0.7.15

    The version of the OpenAPI document: Prod
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from blue_time_python_sdk.type.pay_tools_api_models_card_input_model import PayToolsApiModelsCardInputModel
from blue_time_python_sdk.type.pay_tools_api_models_payer_details_no_ip_address import PayToolsApiModelsPayerDetailsNoIpAddress

class RequiredPayToolsApiModelsCardOpsChargeRequest(TypedDict):
    card: PayToolsApiModelsCardInputModel

class OptionalPayToolsApiModelsCardOpsChargeRequest(TypedDict, total=False):
    payerDetails: PayToolsApiModelsPayerDetailsNoIpAddress

    # Your custom reference for this transaction
    myRef: typing.Optional[str]

class PayToolsApiModelsCardOpsChargeRequest(RequiredPayToolsApiModelsCardOpsChargeRequest, OptionalPayToolsApiModelsCardOpsChargeRequest):
    pass
