# coding: utf-8

"""
    Orchestra API

    Code Version 1.0.7.15

    The version of the OpenAPI document: Prod
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from blue_time_python_sdk.type.system_collections_generic_key_value_pair2_system_string_system_private_core_lib_version6000_cultureneutral_public_key_token7cec85d7bea7798e_system_string_system_private_core_lib_version6000_cultureneutral_public_key_token7cec85d7bea7798e import SystemCollectionsGenericKeyValuePair2SystemStringSystemPrivateCoreLibVersion6000CultureneutralPublicKeyToken7cec85d7bea7798eSystemStringSystemPrivateCoreLibVersion6000CultureneutralPublicKeyToken7cec85d7bea7798e

class RequiredPayToolsApiModelsPaymentGatewayAccount(TypedDict):
    pass

class OptionalPayToolsApiModelsPaymentGatewayAccount(TypedDict, total=False):
    # Unique name of the Payment Gateway the account information relates to.
    paymentGatewayName: typing.Optional[str]

    # A list of key-value pairs that represents your credentials within the Payment gateway.   Each key should represent a parameter listed in the \"CredentialsNames\" element of the response from the list all payment gateways method at `[GET] /paymentGateway`  Example:  \"Credentials\": [     {         \"Key\": \"PrivateKey\",         \"Value\": \"VBtt666M/G098098vgdewvk0Mc-GH\"     }  ]
    credentials: typing.Optional[typing.List[SystemCollectionsGenericKeyValuePair2SystemStringSystemPrivateCoreLibVersion6000CultureneutralPublicKeyToken7cec85d7bea7798eSystemStringSystemPrivateCoreLibVersion6000CultureneutralPublicKeyToken7cec85d7bea7798e]]

class PayToolsApiModelsPaymentGatewayAccount(RequiredPayToolsApiModelsPaymentGatewayAccount, OptionalPayToolsApiModelsPaymentGatewayAccount):
    pass
