# coding: utf-8

"""
    Orchestra API

    Code Version 1.0.7.15

    The version of the OpenAPI document: Prod
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from blue_time_python_sdk.type.pay_tools_bl_authentication_charge_preset_data import PayToolsBlAuthenticationChargePresetData
from blue_time_python_sdk.type.pay_tools_bl_authentication_three_ds_session_model import PayToolsBlAuthenticationThreeDsSessionModel
from blue_time_python_sdk.type.pay_tools_bl_authentication_tokenization_action import PayToolsBlAuthenticationTokenizationAction
from blue_time_python_sdk.type.pay_tools_shared_enums_perform3ds import PayToolsSharedEnumsPerform3ds
from blue_time_python_sdk.type.pci_booking_iin_lookup_library_risk_level import PciBookingIINLookupLibraryRiskLevel

RequiredPayToolsBlAuthenticationPreSignedDataModel = TypedDict("RequiredPayToolsBlAuthenticationPreSignedDataModel", {
    })

OptionalPayToolsBlAuthenticationPreSignedDataModel = TypedDict("OptionalPayToolsBlAuthenticationPreSignedDataModel", {
    "threeDsSessionModel": PayToolsBlAuthenticationThreeDsSessionModel,

    "vld": PciBookingIINLookupLibraryRiskLevel,

    "3ds": PayToolsSharedEnumsPerform3ds,

    # Is Card charge required for this session
    "crg": bool,

    "tkn": PayToolsBlAuthenticationTokenizationAction,

    "crg_d": PayToolsBlAuthenticationChargePresetData,
    }, total=False)

class PayToolsBlAuthenticationPreSignedDataModel(RequiredPayToolsBlAuthenticationPreSignedDataModel, OptionalPayToolsBlAuthenticationPreSignedDataModel):
    pass
