# coding: utf-8

"""
    Orchestra API

    Code Version 1.0.7.15

    The version of the OpenAPI document: Prod
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredPaymentsPayer(TypedDict):
    pass

class OptionalPaymentsPayer(TypedDict, total=False):
    firstName: typing.Optional[str]

    lastName: typing.Optional[str]

    email: typing.Optional[str]

    phone: typing.Optional[str]

    cardOwnerId: typing.Optional[str]

    address1: typing.Optional[str]

    address2: typing.Optional[str]

    address3: typing.Optional[str]

    city: typing.Optional[str]

    stateProvince: typing.Optional[str]

    countryCode: typing.Optional[str]

    postCode: typing.Optional[str]

    clientIPAddress: typing.Optional[str]

    address: typing.Optional[str]

    fullName: typing.Optional[str]

    validIpAddress: typing.Optional[str]

class PaymentsPayer(RequiredPaymentsPayer, OptionalPaymentsPayer):
    pass
