# coding: utf-8

"""
    Orchestra API

    Code Version 1.0.7.15

    The version of the OpenAPI document: Prod
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from blue_time_python_sdk.type.payments_bank_card import PaymentsBankCard
from blue_time_python_sdk.type.payments_money import PaymentsMoney
from blue_time_python_sdk.type.payments_payer import PaymentsPayer
from blue_time_python_sdk.type.payments_three_ds import PaymentsThreeDS

class RequiredPaymentsChargeRequest(TypedDict):
    pass

class OptionalPaymentsChargeRequest(TypedDict, total=False):
    bankCard: PaymentsBankCard

    payer: PaymentsPayer

    threeDS: PaymentsThreeDS

    userToken: typing.Optional[str]

    amount: PaymentsMoney

    myReference: typing.Optional[str]

    isDigitalGoods: bool

    orderDesc: typing.Optional[str]

    generateToken: bool

class PaymentsChargeRequest(RequiredPaymentsChargeRequest, OptionalPaymentsChargeRequest):
    pass
