# coding: utf-8

"""
    Orchestra API

    Code Version 1.0.7.15

    The version of the OpenAPI document: Prod
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from blue_time_python_sdk import schemas  # noqa: F401


class PayToolsBlAuthenticationThreeDsBrand(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    A brand for 3DS authentication
    """


    class MetaOapg:
        required = {
            "bin",
            "mid",
            "mcc",
        }
        
        class properties:
            
            
            class bin(
                schemas.StrSchema
            ):
                pass
            
            
            class mid(
                schemas.StrSchema
            ):
                pass
            
            
            class mcc(
                schemas.StrSchema
            ):
                pass
        
            @staticmethod
            def brd() -> typing.Type['PaymentsCardTypes']:
                return PaymentsCardTypes
            __annotations__ = {
                "bin": bin,
                "mid": mid,
                "mcc": mcc,
                "brd": brd,
            }
    
    bin: MetaOapg.properties.bin
    mid: MetaOapg.properties.mid
    mcc: MetaOapg.properties.mcc
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["bin"]) -> MetaOapg.properties.bin: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["mid"]) -> MetaOapg.properties.mid: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["mcc"]) -> MetaOapg.properties.mcc: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["brd"]) -> 'PaymentsCardTypes': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["bin", "mid", "mcc", "brd", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["bin"]) -> MetaOapg.properties.bin: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["mid"]) -> MetaOapg.properties.mid: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["mcc"]) -> MetaOapg.properties.mcc: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["brd"]) -> typing.Union['PaymentsCardTypes', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["bin", "mid", "mcc", "brd", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        bin: typing.Union[MetaOapg.properties.bin, str, ],
        mid: typing.Union[MetaOapg.properties.mid, str, ],
        mcc: typing.Union[MetaOapg.properties.mcc, str, ],
        brd: typing.Union['PaymentsCardTypes', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'PayToolsBlAuthenticationThreeDsBrand':
        return super().__new__(
            cls,
            *args,
            bin=bin,
            mid=mid,
            mcc=mcc,
            brd=brd,
            _configuration=_configuration,
            **kwargs,
        )

from blue_time_python_sdk.model.payments_card_types import PaymentsCardTypes
