# coding: utf-8

"""
    Orchestra API

    Code Version 1.0.7.15

    The version of the OpenAPI document: Prod
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from blue_time_python_sdk import schemas  # noqa: F401


class PayToolsBlAuthenticationThreeDsSessionModel(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    Data to be used in 3DS authentication request
    """


    class MetaOapg:
        required = {
            "merchantAccountName",
            "amt",
        }
        
        class properties:
            
            
            class merchantAccountName(
                schemas.StrSchema
            ):
            
            
                class MetaOapg:
                    min_length = 1
        
            @staticmethod
            def amt() -> typing.Type['PayToolsSharedModelsMoneyModel']:
                return PayToolsSharedModelsMoneyModel
            __annotations__ = {
                "merchantAccountName": merchantAccountName,
                "amt": amt,
            }
    
    merchantAccountName: MetaOapg.properties.merchantAccountName
    amt: 'PayToolsSharedModelsMoneyModel'
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["merchantAccountName"]) -> MetaOapg.properties.merchantAccountName: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["amt"]) -> 'PayToolsSharedModelsMoneyModel': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["merchantAccountName", "amt", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["merchantAccountName"]) -> MetaOapg.properties.merchantAccountName: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["amt"]) -> 'PayToolsSharedModelsMoneyModel': ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["merchantAccountName", "amt", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        merchantAccountName: typing.Union[MetaOapg.properties.merchantAccountName, str, ],
        amt: 'PayToolsSharedModelsMoneyModel',
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'PayToolsBlAuthenticationThreeDsSessionModel':
        return super().__new__(
            cls,
            *args,
            merchantAccountName=merchantAccountName,
            amt=amt,
            _configuration=_configuration,
            **kwargs,
        )

from blue_time_python_sdk.model.pay_tools_shared_models_money_model import PayToolsSharedModelsMoneyModel
