# coding: utf-8

"""
    Orchestra API

    Code Version 1.0.7.15

    The version of the OpenAPI document: Prod
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from blue_time_python_sdk import schemas  # noqa: F401


class PayToolsApiModelsCardInputModel(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    The card details that should be charged. You can either provide us with the raw card details or provide a reference to the stored card details in a token.
    """


    class MetaOapg:
        required = {
            "expirationYear",
            "cardHolderName",
            "expirationMonth",
            "cardNumber",
        }
        
        class properties:
            
            
            class cardHolderName(
                schemas.StrSchema
            ):
            
            
                class MetaOapg:
                    max_length = 30
                    min_length = 3
            
            
            class cardNumber(
                schemas.StrSchema
            ):
            
            
                class MetaOapg:
                    min_length = 1
                    regex=[{
                        'pattern': r'^(\d{12,20}|@[A-Za-z0-9]{32})$',
                    }]
            expirationYear = schemas.Int32Schema
            
            
            class expirationMonth(
                schemas.Int32Schema
            ):
            
            
                class MetaOapg:
                    format = 'int32'
                    inclusive_maximum = 12
                    inclusive_minimum = 1
            
            
            class ownerID(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'ownerID':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            
            
            class issueNumber(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'issueNumber':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            
            
            class cvv(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                class MetaOapg:
                    regex=[{
                        'pattern': r'^\d{3,4}$',
                    }]
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'cvv':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
        
            @staticmethod
            def threeDSAuthentication() -> typing.Type['PayToolsApiModelsThreeDSAuthenticationInputModel']:
                return PayToolsApiModelsThreeDSAuthenticationInputModel
        
            @staticmethod
            def cardType() -> typing.Type['PaymentsCardTypes']:
                return PaymentsCardTypes
            __annotations__ = {
                "cardHolderName": cardHolderName,
                "cardNumber": cardNumber,
                "expirationYear": expirationYear,
                "expirationMonth": expirationMonth,
                "ownerID": ownerID,
                "issueNumber": issueNumber,
                "cvv": cvv,
                "threeDSAuthentication": threeDSAuthentication,
                "cardType": cardType,
            }
    
    expirationYear: MetaOapg.properties.expirationYear
    cardHolderName: MetaOapg.properties.cardHolderName
    expirationMonth: MetaOapg.properties.expirationMonth
    cardNumber: MetaOapg.properties.cardNumber
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["cardHolderName"]) -> MetaOapg.properties.cardHolderName: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["cardNumber"]) -> MetaOapg.properties.cardNumber: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["expirationYear"]) -> MetaOapg.properties.expirationYear: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["expirationMonth"]) -> MetaOapg.properties.expirationMonth: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["ownerID"]) -> MetaOapg.properties.ownerID: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["issueNumber"]) -> MetaOapg.properties.issueNumber: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["cvv"]) -> MetaOapg.properties.cvv: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["threeDSAuthentication"]) -> 'PayToolsApiModelsThreeDSAuthenticationInputModel': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["cardType"]) -> 'PaymentsCardTypes': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["cardHolderName", "cardNumber", "expirationYear", "expirationMonth", "ownerID", "issueNumber", "cvv", "threeDSAuthentication", "cardType", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["cardHolderName"]) -> MetaOapg.properties.cardHolderName: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["cardNumber"]) -> MetaOapg.properties.cardNumber: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["expirationYear"]) -> MetaOapg.properties.expirationYear: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["expirationMonth"]) -> MetaOapg.properties.expirationMonth: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["ownerID"]) -> typing.Union[MetaOapg.properties.ownerID, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["issueNumber"]) -> typing.Union[MetaOapg.properties.issueNumber, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["cvv"]) -> typing.Union[MetaOapg.properties.cvv, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["threeDSAuthentication"]) -> typing.Union['PayToolsApiModelsThreeDSAuthenticationInputModel', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["cardType"]) -> typing.Union['PaymentsCardTypes', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["cardHolderName", "cardNumber", "expirationYear", "expirationMonth", "ownerID", "issueNumber", "cvv", "threeDSAuthentication", "cardType", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        expirationYear: typing.Union[MetaOapg.properties.expirationYear, decimal.Decimal, int, ],
        cardHolderName: typing.Union[MetaOapg.properties.cardHolderName, str, ],
        expirationMonth: typing.Union[MetaOapg.properties.expirationMonth, decimal.Decimal, int, ],
        cardNumber: typing.Union[MetaOapg.properties.cardNumber, str, ],
        ownerID: typing.Union[MetaOapg.properties.ownerID, None, str, schemas.Unset] = schemas.unset,
        issueNumber: typing.Union[MetaOapg.properties.issueNumber, None, str, schemas.Unset] = schemas.unset,
        cvv: typing.Union[MetaOapg.properties.cvv, None, str, schemas.Unset] = schemas.unset,
        threeDSAuthentication: typing.Union['PayToolsApiModelsThreeDSAuthenticationInputModel', schemas.Unset] = schemas.unset,
        cardType: typing.Union['PaymentsCardTypes', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'PayToolsApiModelsCardInputModel':
        return super().__new__(
            cls,
            *args,
            expirationYear=expirationYear,
            cardHolderName=cardHolderName,
            expirationMonth=expirationMonth,
            cardNumber=cardNumber,
            ownerID=ownerID,
            issueNumber=issueNumber,
            cvv=cvv,
            threeDSAuthentication=threeDSAuthentication,
            cardType=cardType,
            _configuration=_configuration,
            **kwargs,
        )

from blue_time_python_sdk.model.pay_tools_api_models_three_ds_authentication_input_model import PayToolsApiModelsThreeDSAuthenticationInputModel
from blue_time_python_sdk.model.payments_card_types import PaymentsCardTypes
