# coding: utf-8

"""
    Orchestra API

    Code Version 1.0.7.15

    The version of the OpenAPI document: Prod
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from blue_time_python_sdk import schemas  # noqa: F401


class PayToolsApiModelsCardOpsChargeRequest(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    Model for a Charge request for card processing via a payment gateway using Card operations
    """


    class MetaOapg:
        required = {
            "card",
        }
        
        class properties:
        
            @staticmethod
            def card() -> typing.Type['PayToolsApiModelsCardInputModel']:
                return PayToolsApiModelsCardInputModel
        
            @staticmethod
            def payerDetails() -> typing.Type['PayToolsApiModelsPayerDetailsNoIpAddress']:
                return PayToolsApiModelsPayerDetailsNoIpAddress
            
            
            class myRef(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'myRef':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            __annotations__ = {
                "card": card,
                "payerDetails": payerDetails,
                "myRef": myRef,
            }
    
    card: 'PayToolsApiModelsCardInputModel'
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["card"]) -> 'PayToolsApiModelsCardInputModel': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["payerDetails"]) -> 'PayToolsApiModelsPayerDetailsNoIpAddress': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["myRef"]) -> MetaOapg.properties.myRef: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["card", "payerDetails", "myRef", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["card"]) -> 'PayToolsApiModelsCardInputModel': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["payerDetails"]) -> typing.Union['PayToolsApiModelsPayerDetailsNoIpAddress', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["myRef"]) -> typing.Union[MetaOapg.properties.myRef, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["card", "payerDetails", "myRef", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        card: 'PayToolsApiModelsCardInputModel',
        payerDetails: typing.Union['PayToolsApiModelsPayerDetailsNoIpAddress', schemas.Unset] = schemas.unset,
        myRef: typing.Union[MetaOapg.properties.myRef, None, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'PayToolsApiModelsCardOpsChargeRequest':
        return super().__new__(
            cls,
            *args,
            card=card,
            payerDetails=payerDetails,
            myRef=myRef,
            _configuration=_configuration,
            **kwargs,
        )

from blue_time_python_sdk.model.pay_tools_api_models_card_input_model import PayToolsApiModelsCardInputModel
from blue_time_python_sdk.model.pay_tools_api_models_payer_details_no_ip_address import PayToolsApiModelsPayerDetailsNoIpAddress
