# coding: utf-8

"""
    Orchestra API

    Code Version 1.0.7.15

    The version of the OpenAPI document: Prod
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from blue_time_python_sdk import schemas  # noqa: F401


class PayToolsBlAuthenticationPreSignedDataModel(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    Model for initial request for a Card operation session
    """


    class MetaOapg:
        
        class properties:
        
            @staticmethod
            def threeDsSessionModel() -> typing.Type['PayToolsBlAuthenticationThreeDsSessionModel']:
                return PayToolsBlAuthenticationThreeDsSessionModel
        
            @staticmethod
            def vld() -> typing.Type['PciBookingIINLookupLibraryRiskLevel']:
                return PciBookingIINLookupLibraryRiskLevel
        
            @staticmethod
            def _3ds() -> typing.Type['PayToolsSharedEnumsPerform3ds']:
                return PayToolsSharedEnumsPerform3ds
            crg = schemas.BoolSchema
        
            @staticmethod
            def tkn() -> typing.Type['PayToolsBlAuthenticationTokenizationAction']:
                return PayToolsBlAuthenticationTokenizationAction
        
            @staticmethod
            def crg_d() -> typing.Type['PayToolsBlAuthenticationChargePresetData']:
                return PayToolsBlAuthenticationChargePresetData
            __annotations__ = {
                "threeDsSessionModel": threeDsSessionModel,
                "vld": vld,
                "3ds": _3ds,
                "crg": crg,
                "tkn": tkn,
                "crg_d": crg_d,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["threeDsSessionModel"]) -> 'PayToolsBlAuthenticationThreeDsSessionModel': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["vld"]) -> 'PciBookingIINLookupLibraryRiskLevel': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["3ds"]) -> 'PayToolsSharedEnumsPerform3ds': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["crg"]) -> MetaOapg.properties.crg: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["tkn"]) -> 'PayToolsBlAuthenticationTokenizationAction': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["crg_d"]) -> 'PayToolsBlAuthenticationChargePresetData': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["threeDsSessionModel", "vld", "3ds", "crg", "tkn", "crg_d", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["threeDsSessionModel"]) -> typing.Union['PayToolsBlAuthenticationThreeDsSessionModel', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["vld"]) -> typing.Union['PciBookingIINLookupLibraryRiskLevel', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["3ds"]) -> typing.Union['PayToolsSharedEnumsPerform3ds', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["crg"]) -> typing.Union[MetaOapg.properties.crg, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["tkn"]) -> typing.Union['PayToolsBlAuthenticationTokenizationAction', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["crg_d"]) -> typing.Union['PayToolsBlAuthenticationChargePresetData', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["threeDsSessionModel", "vld", "3ds", "crg", "tkn", "crg_d", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        threeDsSessionModel: typing.Union['PayToolsBlAuthenticationThreeDsSessionModel', schemas.Unset] = schemas.unset,
        vld: typing.Union['PciBookingIINLookupLibraryRiskLevel', schemas.Unset] = schemas.unset,
        crg: typing.Union[MetaOapg.properties.crg, bool, schemas.Unset] = schemas.unset,
        tkn: typing.Union['PayToolsBlAuthenticationTokenizationAction', schemas.Unset] = schemas.unset,
        crg_d: typing.Union['PayToolsBlAuthenticationChargePresetData', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'PayToolsBlAuthenticationPreSignedDataModel':
        return super().__new__(
            cls,
            *args,
            threeDsSessionModel=threeDsSessionModel,
            vld=vld,
            crg=crg,
            tkn=tkn,
            crg_d=crg_d,
            _configuration=_configuration,
            **kwargs,
        )

from blue_time_python_sdk.model.pay_tools_bl_authentication_charge_preset_data import PayToolsBlAuthenticationChargePresetData
from blue_time_python_sdk.model.pay_tools_bl_authentication_three_ds_session_model import PayToolsBlAuthenticationThreeDsSessionModel
from blue_time_python_sdk.model.pay_tools_bl_authentication_tokenization_action import PayToolsBlAuthenticationTokenizationAction
from blue_time_python_sdk.model.pay_tools_shared_enums_perform3ds import PayToolsSharedEnumsPerform3ds
from blue_time_python_sdk.model.pci_booking_iin_lookup_library_risk_level import PciBookingIINLookupLibraryRiskLevel
