# coding: utf-8

"""
    Orchestra API

    Code Version 1.0.7.15

    The version of the OpenAPI document: Prod
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from blue_time_python_sdk import schemas  # noqa: F401


class PayToolsSharedModelsMoneyModel(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    Represents an amount in a given currency
    """


    class MetaOapg:
        required = {
            "cur",
            "amt",
        }
        
        class properties:
        
            @staticmethod
            def cur() -> typing.Type['PaymentsCurrencyCode']:
                return PaymentsCurrencyCode
            amt = schemas.Float64Schema
            __annotations__ = {
                "cur": cur,
                "amt": amt,
            }
    
    cur: 'PaymentsCurrencyCode'
    amt: MetaOapg.properties.amt
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["cur"]) -> 'PaymentsCurrencyCode': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["amt"]) -> MetaOapg.properties.amt: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["cur", "amt", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["cur"]) -> 'PaymentsCurrencyCode': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["amt"]) -> MetaOapg.properties.amt: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["cur", "amt", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        cur: 'PaymentsCurrencyCode',
        amt: typing.Union[MetaOapg.properties.amt, decimal.Decimal, int, float, ],
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'PayToolsSharedModelsMoneyModel':
        return super().__new__(
            cls,
            *args,
            cur=cur,
            amt=amt,
            _configuration=_configuration,
            **kwargs,
        )

from blue_time_python_sdk.model.payments_currency_code import PaymentsCurrencyCode
