# coding: utf-8

"""
    Orchestra API

    Code Version 1.0.7.15

    The version of the OpenAPI document: Prod
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from blue_time_python_sdk import schemas  # noqa: F401


class PayToolsApiModelsCvvOpsChargeRequest(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    Model for a Charge request of an existing card after capturing security code (CVV) for card processing via a payment gateway using Card operations
    """


    class MetaOapg:
        required = {
            "cvv",
        }
        
        class properties:
            
            
            class cvv(
                schemas.StrSchema
            ):
                pass
            __annotations__ = {
                "cvv": cvv,
            }
    
    cvv: MetaOapg.properties.cvv
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["cvv"]) -> MetaOapg.properties.cvv: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["cvv", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["cvv"]) -> MetaOapg.properties.cvv: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["cvv", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        cvv: typing.Union[MetaOapg.properties.cvv, str, ],
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'PayToolsApiModelsCvvOpsChargeRequest':
        return super().__new__(
            cls,
            *args,
            cvv=cvv,
            _configuration=_configuration,
            **kwargs,
        )
