# coding: utf-8

"""
    Orchestra API

    Code Version 1.0.7.15

    The version of the OpenAPI document: Prod
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from blue_time_python_sdk import schemas  # noqa: F401


class PayToolsBlAuthenticationThreeDsPresetData(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    Data to be used in 3DS authentication request
    """


    class MetaOapg:
        
        class properties:
            
            
            class sid(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'sid':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
        
            @staticmethod
            def mrc() -> typing.Type['PayToolsBlAuthenticationThreeDMerchant']:
                return PayToolsBlAuthenticationThreeDMerchant
        
            @staticmethod
            def amt() -> typing.Type['PayToolsSharedModelsMoneyModel']:
                return PayToolsSharedModelsMoneyModel
            __annotations__ = {
                "sid": sid,
                "mrc": mrc,
                "amt": amt,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["sid"]) -> MetaOapg.properties.sid: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["mrc"]) -> 'PayToolsBlAuthenticationThreeDMerchant': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["amt"]) -> 'PayToolsSharedModelsMoneyModel': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["sid", "mrc", "amt", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["sid"]) -> typing.Union[MetaOapg.properties.sid, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["mrc"]) -> typing.Union['PayToolsBlAuthenticationThreeDMerchant', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["amt"]) -> typing.Union['PayToolsSharedModelsMoneyModel', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["sid", "mrc", "amt", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        sid: typing.Union[MetaOapg.properties.sid, None, str, schemas.Unset] = schemas.unset,
        mrc: typing.Union['PayToolsBlAuthenticationThreeDMerchant', schemas.Unset] = schemas.unset,
        amt: typing.Union['PayToolsSharedModelsMoneyModel', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'PayToolsBlAuthenticationThreeDsPresetData':
        return super().__new__(
            cls,
            *args,
            sid=sid,
            mrc=mrc,
            amt=amt,
            _configuration=_configuration,
            **kwargs,
        )

from blue_time_python_sdk.model.pay_tools_bl_authentication_three_d_merchant import PayToolsBlAuthenticationThreeDMerchant
from blue_time_python_sdk.model.pay_tools_shared_models_money_model import PayToolsSharedModelsMoneyModel
