# coding: utf-8

"""
    Orchestra API

    Code Version 1.0.7.15

    The version of the OpenAPI document: Prod
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from blue_time_python_sdk import schemas  # noqa: F401


class PaymentsOperation(
    schemas.EnumBase,
    schemas.StrSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    
    @schemas.classproperty
    def CHARGE(cls):
        return cls("Charge")
    
    @schemas.classproperty
    def PRE_AUTH(cls):
        return cls("PreAuth")
    
    @schemas.classproperty
    def CAPTURE(cls):
        return cls("Capture")
    
    @schemas.classproperty
    def VOID(cls):
        return cls("Void")
    
    @schemas.classproperty
    def REFUND(cls):
        return cls("Refund")
    
    @schemas.classproperty
    def TOKENIZE(cls):
        return cls("Tokenize")
