# coding: utf-8

"""
    Orchestra API

    Code Version 1.0.7.15

    The version of the OpenAPI document: Prod
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from blue_time_python_sdk import schemas  # noqa: F401


class PaymentGatewayAccountsGetAllResponse(
    schemas.ListSchema
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        @staticmethod
        def items() -> typing.Type['PayToolsApiModelsPaymentGatewayAccountBriefOutputModel']:
            return PayToolsApiModelsPaymentGatewayAccountBriefOutputModel

    def __new__(
        cls,
        arg: typing.Union[typing.Tuple['PayToolsApiModelsPaymentGatewayAccountBriefOutputModel'], typing.List['PayToolsApiModelsPaymentGatewayAccountBriefOutputModel']],
        _configuration: typing.Optional[schemas.Configuration] = None,
    ) -> 'PaymentGatewayAccountsGetAllResponse':
        return super().__new__(
            cls,
            arg,
            _configuration=_configuration,
        )

    def __getitem__(self, i: int) -> 'PayToolsApiModelsPaymentGatewayAccountBriefOutputModel':
        return super().__getitem__(i)

from blue_time_python_sdk.model.pay_tools_api_models_payment_gateway_account_brief_output_model import PayToolsApiModelsPaymentGatewayAccountBriefOutputModel
