# coding: utf-8

"""
    Orchestra API

    Code Version 1.0.7.15

    The version of the OpenAPI document: Prod
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from blue_time_python_sdk import schemas  # noqa: F401


class PaymentsBankCardBase(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
            
            
            class number(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'number':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            expirationMonth = schemas.Int32Schema
            expirationYear = schemas.Int32Schema
            __annotations__ = {
                "number": number,
                "expirationMonth": expirationMonth,
                "expirationYear": expirationYear,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["number"]) -> MetaOapg.properties.number: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["expirationMonth"]) -> MetaOapg.properties.expirationMonth: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["expirationYear"]) -> MetaOapg.properties.expirationYear: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["number", "expirationMonth", "expirationYear", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["number"]) -> typing.Union[MetaOapg.properties.number, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["expirationMonth"]) -> typing.Union[MetaOapg.properties.expirationMonth, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["expirationYear"]) -> typing.Union[MetaOapg.properties.expirationYear, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["number", "expirationMonth", "expirationYear", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        number: typing.Union[MetaOapg.properties.number, None, str, schemas.Unset] = schemas.unset,
        expirationMonth: typing.Union[MetaOapg.properties.expirationMonth, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        expirationYear: typing.Union[MetaOapg.properties.expirationYear, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'PaymentsBankCardBase':
        return super().__new__(
            cls,
            *args,
            number=number,
            expirationMonth=expirationMonth,
            expirationYear=expirationYear,
            _configuration=_configuration,
            **kwargs,
        )
