# coding: utf-8

"""
    Orchestra API

    Code Version 1.0.7.15

    The version of the OpenAPI document: Prod
    Generated by: https://konfigthis.com
"""

import unittest
from unittest.mock import patch

import urllib3

import blue_time_python_sdk
from blue_time_python_sdk.paths.three_ds_sessions_fingerprint_callback_session_id import post
from blue_time_python_sdk import configuration, schemas, api_client

from .. import ApiTestMixin


class TestThreeDsSessionsFingerprintCallbackSessionId(ApiTestMixin, unittest.TestCase):
    """
    ThreeDsSessionsFingerprintCallbackSessionId unit test stubs
        Handle a callback (redirect from device fingerprint)
    """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    response_status = 200
    response_body = ''


if __name__ == '__main__':
    unittest.main()
