# coding: utf-8

"""
    Orchestra API

    Code Version 1.0.7.15

    The version of the OpenAPI document: Prod
    Generated by: https://konfigthis.com
"""

import unittest
from unittest.mock import patch

import urllib3

import blue_time_python_sdk
from blue_time_python_sdk.paths.payment_gateway_accounts_name import delete
from blue_time_python_sdk import configuration, schemas, api_client

from .. import ApiTestMixin


class TestPaymentGatewayAccountsName(ApiTestMixin, unittest.TestCase):
    """
    PaymentGatewayAccountsName unit test stubs
        Delete a Payment Gateway Account
    """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    response_status = 200
    response_body = ''


if __name__ == '__main__':
    unittest.main()
