# coding: utf-8

"""
    Orchestra API

    Code Version 1.0.7.15

    The version of the OpenAPI document: Prod
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from blue_time_python_sdk.pydantic.custom_forms_upload_form_folder_request_headers import CustomFormsUploadFormFolderRequestHeaders

class CustomFormsUploadFormFolderRequest(BaseModel):
    content_type: typing.Optional[str] = Field(None, alias='ContentType')

    content_disposition: typing.Optional[str] = Field(None, alias='ContentDisposition')

    headers: typing.Optional[CustomFormsUploadFormFolderRequestHeaders] = Field(None, alias='Headers')

    length: typing.Optional[int] = Field(None, alias='Length')

    name: typing.Optional[str] = Field(None, alias='Name')

    file_name: typing.Optional[str] = Field(None, alias='FileName')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
