# coding: utf-8

"""
    Orchestra API

    Code Version 1.0.7.15

    The version of the OpenAPI document: Prod
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict


class PayToolsApiModelsCustomFormMetaModel(BaseModel):
    # Time the Custom Form was initially created
    creation_time: typing.Optional[datetime] = Field(None, alias='creationTime')

    # Time the Custom Form was lastly updated
    update_time: typing.Optional[typing.Optional[datetime]] = Field(None, alias='updateTime')

    # The Custom Form name. It should be used for referencing the form for management and for usage
    name: typing.Optional[typing.Optional[str]] = Field(None, alias='name')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
