# coding: utf-8

"""
    Orchestra API

    Code Version 1.0.7.15

    The version of the OpenAPI document: Prod
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from blue_time_python_sdk.pydantic.pay_tools_shared_models_money_model import PayToolsSharedModelsMoneyModel

class PayToolsBlAuthenticationChargePresetData(BaseModel):
    # Order description
    dsc: typing.Optional[typing.Optional[str]] = Field(None, alias='dsc')

    # Creator reference
    ref: typing.Optional[typing.Optional[str]] = Field(None, alias='ref')

    # Is it digital goods
    dig: typing.Optional[bool] = Field(None, alias='dig')

    amt: typing.Optional[PayToolsSharedModelsMoneyModel] = Field(None, alias='amt')

    # The Upg Account name
    uan: typing.Optional[typing.Optional[str]] = Field(None, alias='uan')

    # The Upg Client Certificate name
    ucc: typing.Optional[typing.Optional[str]] = Field(None, alias='ucc')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
