# coding: utf-8

"""
    Orchestra API

    Code Version 1.0.7.15

    The version of the OpenAPI document: Prod
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from blue_time_python_sdk.pydantic.pay_tools_bl_authentication_charge_preset_data import PayToolsBlAuthenticationChargePresetData
from blue_time_python_sdk.pydantic.pay_tools_bl_authentication_three_ds_preset_data import PayToolsBlAuthenticationThreeDsPresetData
from blue_time_python_sdk.pydantic.pay_tools_bl_authentication_tokenization_action import PayToolsBlAuthenticationTokenizationAction
from blue_time_python_sdk.pydantic.pay_tools_shared_enums_perform3ds import PayToolsSharedEnumsPerform3ds
from blue_time_python_sdk.pydantic.payments_charge_request import PaymentsChargeRequest
from blue_time_python_sdk.pydantic.payments_operation_result import PaymentsOperationResult
from blue_time_python_sdk.pydantic.pci_booking_iin_lookup_library_card_validation_request import PciBookingIINLookupLibraryCardValidationRequest
from blue_time_python_sdk.pydantic.pci_booking_iin_lookup_library_card_validation_result import PciBookingIINLookupLibraryCardValidationResult
from blue_time_python_sdk.pydantic.pci_booking_iin_lookup_library_risk_level import PciBookingIINLookupLibraryRiskLevel

class PayToolsBlAuthenticationSignedData(BaseModel):
    vld_rq: typing.Optional[PciBookingIINLookupLibraryCardValidationRequest] = Field(None, alias='vld_rq')

    vld_rs: typing.Optional[PciBookingIINLookupLibraryCardValidationResult] = Field(None, alias='vld_rs')

    crg_rq: typing.Optional[PaymentsChargeRequest] = Field(None, alias='crg_rq')

    crg_rs: typing.Optional[PaymentsOperationResult] = Field(None, alias='crg_rs')

    # Result from tokenization
    tkn_rs: typing.Optional[typing.Optional[str]] = Field(None, alias='tkn_rs')

    3ds_d_: typing.Optional[PayToolsBlAuthenticationThreeDsPresetData] = Field(None, alias='3ds_d')

    vld: typing.Optional[PciBookingIINLookupLibraryRiskLevel] = Field(None, alias='vld')

    3ds_: typing.Optional[PayToolsSharedEnumsPerform3ds] = Field(None, alias='3ds')

    # Is Card charge required for this session
    crg: typing.Optional[bool] = Field(None, alias='crg')

    tkn: typing.Optional[PayToolsBlAuthenticationTokenizationAction] = Field(None, alias='tkn')

    crg_d: typing.Optional[PayToolsBlAuthenticationChargePresetData] = Field(None, alias='crg_d')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
