# coding: utf-8

"""
    Orchestra API

    Code Version 1.0.7.15

    The version of the OpenAPI document: Prod
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from blue_time_python_sdk.pydantic.pay_tools_dal_entities_three_ds_brand import PayToolsDalEntitiesThreeDsBrand

class PayToolsDalEntitiesThreeDsMerchant(BaseModel):
    merchant_name: str = Field(alias='merchantName')

    merchant_display_name: str = Field(alias='merchantDisplayName')

    merchant_requestor_id_suffix: str = Field(alias='merchantRequestorIdSuffix')

    merchant_country: str = Field(alias='merchantCountry')

    merchant_url: str = Field(alias='merchantUrl')

    acquirer_name: str = Field(alias='acquirerName')

    brands: typing.Optional[typing.Optional[typing.List[PayToolsDalEntitiesThreeDsBrand]]] = Field(None, alias='brands')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
