# coding: utf-8

"""
    Orchestra API

    Code Version 1.0.7.15

    The version of the OpenAPI document: Prod
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from blue_time_python_sdk.pydantic.pay_tools_bl_authentication_three_d_merchant import PayToolsBlAuthenticationThreeDMerchant
from blue_time_python_sdk.pydantic.pay_tools_shared_models_money_model import PayToolsSharedModelsMoneyModel

class PayToolsBlAuthenticationThreeDsPresetData(BaseModel):
    # Session Id with MPI
    sid: typing.Optional[typing.Optional[str]] = Field(None, alias='sid')

    mrc: typing.Optional[PayToolsBlAuthenticationThreeDMerchant] = Field(None, alias='mrc')

    amt: typing.Optional[PayToolsSharedModelsMoneyModel] = Field(None, alias='amt')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
