# coding: utf-8

"""
    Orchestra API

    Code Version 1.0.7.15

    The version of the OpenAPI document: Prod
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from blue_time_python_sdk.pydantic.pay_tools_dal_entities_three_ds_merchant import PayToolsDalEntitiesThreeDsMerchant

class PayToolsApiModelsThreeDsMerchantOutputModel(BaseModel):
    # Account name (Name on system)
    name: typing.Optional[typing.Optional[str]] = Field(None, alias='name')

    three_ds_merchant: typing.Optional[PayToolsDalEntitiesThreeDsMerchant] = Field(None, alias='threeDsMerchant')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
