# coding: utf-8

"""
    Orchestra API

    Code Version 1.0.7.15

    The version of the OpenAPI document: Prod
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from blue_time_python_sdk.pydantic.pay_tools_shared_models_money_model import PayToolsSharedModelsMoneyModel

class PayToolsBlAuthenticationThreeDsSessionModel(BaseModel):
    # The name of the stored merchant account
    merchant_account_name: str = Field(alias='merchantAccountName')

    amt: PayToolsSharedModelsMoneyModel = Field(alias='amt')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
