# coding: utf-8

"""
    Orchestra API

    Code Version 1.0.7.15

    The version of the OpenAPI document: Prod
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from blue_time_python_sdk.pydantic.pay_tools_bl_authentication_three_ds_brand import PayToolsBlAuthenticationThreeDsBrand

class PayToolsBlAuthenticationThreeDMerchant(BaseModel):
    # Merchant name
    mnm: str = Field(alias='mnm')

    # Merchant's display name
    mds: str = Field(alias='mds')

    # Merchant's Requestor Id suffix
    msf: str = Field(alias='msf')

    # Merchant's Country (3-digit ISO 3166-1 numeric)
    cnt: str = Field(alias='cnt')

    # Merchant's Url
    url: str = Field(alias='url')

    # List of supported brands
    brds: typing.List[PayToolsBlAuthenticationThreeDsBrand] = Field(alias='brds')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
