# coding: utf-8

"""
    Orchestra API

    Code Version 1.0.7.15

    The version of the OpenAPI document: Prod
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from blue_time_python_sdk.pydantic.payments_card_types import PaymentsCardTypes

class PayToolsDalEntitiesThreeDsBrand(BaseModel):
    bin: str = Field(alias='bin')

    merchant_id: str = Field(alias='merchantId')

    mcc: str = Field(alias='mcc')

    brand: typing.Optional[PaymentsCardTypes] = Field(None, alias='brand')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
