# coding: utf-8

"""
    Orchestra API

    Code Version 1.0.7.15

    The version of the OpenAPI document: Prod
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from blue_time_python_sdk.pydantic.network_token_request_source import NetworkTokenRequestSource
from blue_time_python_sdk.pydantic.payments_network_token_schemes import PaymentsNetworkTokenSchemes

class PayToolsApiModelsNetworkTokenizationDeleteTokenRequest(BaseModel):
    source: NetworkTokenRequestSource = Field(alias='source')

    # Token Id within the Brand
    token_id: str = Field(alias='tokenId')

    brand: typing.Optional[PaymentsNetworkTokenSchemes] = Field(None, alias='brand')

    # Reason for deletion
    reason: typing.Optional[typing.Optional[str]] = Field(None, alias='reason')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
