# coding: utf-8

"""
    Orchestra API

    Code Version 1.0.7.15

    The version of the OpenAPI document: Prod
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict


class PayToolsApiModelsCardBaseWithSecurityCode(BaseModel):
    # Card number (PAN) or a Reference to a Tokenized string. A Token should be referenced in the format @TOKEN, e.g \"@nQGywsQE9gbURtrXEjTZwtWqeMdK9nsO\"
    card_number: str = Field(alias='cardNumber')

    # Expiration year
    expiration_year: int = Field(alias='expirationYear')

    # Expiration month
    expiration_month: int = Field(alias='expirationMonth')

    # Card security code (digits on back of card)
    cvv: typing.Optional[typing.Optional[str]] = Field(None, alias='cvv')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
