# coding: utf-8

"""
    Orchestra API

    Code Version 1.0.7.15

    The version of the OpenAPI document: Prod
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from blue_time_python_sdk.pydantic.pay_tools_bl_authentication_charge_preset_data import PayToolsBlAuthenticationChargePresetData
from blue_time_python_sdk.pydantic.pay_tools_shared_models_card_stored_card import PayToolsSharedModelsCardStoredCard

class PayToolsBlAuthenticationCvvSignedDataModel(BaseModel):
    card: typing.Optional[PayToolsSharedModelsCardStoredCard] = Field(None, alias='card')

    crg_d: typing.Optional[PayToolsBlAuthenticationChargePresetData] = Field(None, alias='crg_d')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
