# coding: utf-8

"""
    Orchestra API

    Code Version 1.0.7.15

    The version of the OpenAPI document: Prod
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from blue_time_python_sdk.pydantic.system_collections_generic_key_value_pair2_system_string_system_private_core_lib_version6000_cultureneutral_public_key_token7cec85d7bea7798e_system_string_system_private_core_lib_version6000_cultureneutral_public_key_token7cec85d7bea7798e import SystemCollectionsGenericKeyValuePair2SystemStringSystemPrivateCoreLibVersion6000CultureneutralPublicKeyToken7cec85d7bea7798eSystemStringSystemPrivateCoreLibVersion6000CultureneutralPublicKeyToken7cec85d7bea7798e

class PayToolsApiModelsPaymentGatewayAccountInputModel(BaseModel):
    # Unique name of the Payment Gateway the account information relates to.
    payment_gateway_name: typing.Optional[typing.Optional[str]] = Field(None, alias='paymentGatewayName')

    # A list of key-value pairs that represents your credentials within the Payment gateway.   Each key should represent a parameter listed in the \"CredentialsNames\" element of the response from the list all payment gateways method at `[GET] /paymentGateway`  Example:  \"Credentials\": [     {         \"Key\": \"PrivateKey\",         \"Value\": \"VBtt666M/G098098vgdewvk0Mc-GH\"     }  ]
    credentials: typing.Optional[typing.Optional[typing.List[SystemCollectionsGenericKeyValuePair2SystemStringSystemPrivateCoreLibVersion6000CultureneutralPublicKeyToken7cec85d7bea7798eSystemStringSystemPrivateCoreLibVersion6000CultureneutralPublicKeyToken7cec85d7bea7798e]]] = Field(None, alias='credentials')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
