# coding: utf-8

"""
    Orchestra API

    Code Version 1.0.7.15

    The version of the OpenAPI document: Prod
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from blue_time_python_sdk.pydantic.pay_tools_api_models_card_input_model import PayToolsApiModelsCardInputModel
from blue_time_python_sdk.pydantic.pay_tools_api_models_payer_details_no_ip_address import PayToolsApiModelsPayerDetailsNoIpAddress

class PayToolsApiModelsCardOpsChargeRequest(BaseModel):
    card: PayToolsApiModelsCardInputModel = Field(alias='card')

    payer_details: typing.Optional[PayToolsApiModelsPayerDetailsNoIpAddress] = Field(None, alias='payerDetails')

    # Your custom reference for this transaction
    my_ref: typing.Optional[typing.Optional[str]] = Field(None, alias='myRef')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
