# coding: utf-8

"""
    Orchestra API

    Code Version 1.0.7.15

    The version of the OpenAPI document: Prod
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from blue_time_python_sdk.pydantic.payments_card_types import PaymentsCardTypes

class PayToolsBlAuthenticationThreeDsBrand(BaseModel):
    # Brand's Bin
    bin: str = Field(alias='bin')

    # Merchant Id
    mid: str = Field(alias='mid')

    # Brand's MCC
    mcc: str = Field(alias='mcc')

    brd: typing.Optional[PaymentsCardTypes] = Field(None, alias='brd')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
