# coding: utf-8

"""
    Orchestra API

    Code Version 1.0.7.15

    The version of the OpenAPI document: Prod
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict


class PaymentsPayer(BaseModel):
    first_name: typing.Optional[typing.Optional[str]] = Field(None, alias='firstName')

    last_name: typing.Optional[typing.Optional[str]] = Field(None, alias='lastName')

    email: typing.Optional[typing.Optional[str]] = Field(None, alias='email')

    phone: typing.Optional[typing.Optional[str]] = Field(None, alias='phone')

    card_owner_id: typing.Optional[typing.Optional[str]] = Field(None, alias='cardOwnerId')

    address1: typing.Optional[typing.Optional[str]] = Field(None, alias='address1')

    address2: typing.Optional[typing.Optional[str]] = Field(None, alias='address2')

    address3: typing.Optional[typing.Optional[str]] = Field(None, alias='address3')

    city: typing.Optional[typing.Optional[str]] = Field(None, alias='city')

    state_province: typing.Optional[typing.Optional[str]] = Field(None, alias='stateProvince')

    country_code: typing.Optional[typing.Optional[str]] = Field(None, alias='countryCode')

    post_code: typing.Optional[typing.Optional[str]] = Field(None, alias='postCode')

    client_i_p_address: typing.Optional[typing.Optional[str]] = Field(None, alias='clientIPAddress')

    address: typing.Optional[typing.Optional[str]] = Field(None, alias='address')

    full_name: typing.Optional[typing.Optional[str]] = Field(None, alias='fullName')

    valid_ip_address: typing.Optional[typing.Optional[str]] = Field(None, alias='validIpAddress')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
