# coding: utf-8

"""
    Orchestra API

    Code Version 1.0.7.15

    The version of the OpenAPI document: Prod
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from blue_time_python_sdk.pydantic.payments_bank_card import PaymentsBankCard
from blue_time_python_sdk.pydantic.payments_money import PaymentsMoney
from blue_time_python_sdk.pydantic.payments_payer import PaymentsPayer
from blue_time_python_sdk.pydantic.payments_three_ds import PaymentsThreeDS

class PaymentsChargeRequest(BaseModel):
    bank_card: typing.Optional[PaymentsBankCard] = Field(None, alias='bankCard')

    payer: typing.Optional[PaymentsPayer] = Field(None, alias='payer')

    three_d_s: typing.Optional[PaymentsThreeDS] = Field(None, alias='threeDS')

    user_token: typing.Optional[typing.Optional[str]] = Field(None, alias='userToken')

    amount: typing.Optional[PaymentsMoney] = Field(None, alias='amount')

    my_reference: typing.Optional[typing.Optional[str]] = Field(None, alias='myReference')

    is_digital_goods: typing.Optional[bool] = Field(None, alias='isDigitalGoods')

    order_desc: typing.Optional[typing.Optional[str]] = Field(None, alias='orderDesc')

    generate_token: typing.Optional[bool] = Field(None, alias='generateToken')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
