# coding: utf-8

"""
    Orchestra API

    Code Version 1.0.7.15

    The version of the OpenAPI document: Prod
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from blue_time_python_sdk.pydantic.payments_currency_code import PaymentsCurrencyCode

class PaymentsMoney(BaseModel):
    amount: typing.Optional[typing.Union[int, float]] = Field(None, alias='amount')

    currency_code: typing.Optional[PaymentsCurrencyCode] = Field(None, alias='currencyCode')

    iso4217_currency_number: typing.Optional[typing.Optional[str]] = Field(None, alias='iso4217CurrencyNumber')

    amount_in_largest_units: typing.Optional[typing.Union[int, float]] = Field(None, alias='amountInLargestUnits')

    formatted_amount: typing.Optional[typing.Optional[str]] = Field(None, alias='formattedAmount')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
