# coding: utf-8

"""
    Orchestra API

    Code Version 1.0.7.15

    The version of the OpenAPI document: Prod
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict


class PaymentsBankCardBase(BaseModel):
    number: typing.Optional[typing.Optional[str]] = Field(None, alias='number')

    expiration_month: typing.Optional[int] = Field(None, alias='expirationMonth')

    expiration_year: typing.Optional[int] = Field(None, alias='expirationYear')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
