# coding: utf-8

"""
    Orchestra API

    Code Version 1.0.7.15

    The version of the OpenAPI document: Prod
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from blue_time_python_sdk.pydantic.payments_card_types import PaymentsCardTypes

class PaymentsBankCard(BaseModel):
    type: typing.Optional[PaymentsCardTypes] = Field(None, alias='type')

    name_on_card: typing.Optional[typing.Optional[str]] = Field(None, alias='nameOnCard')

    issue_number: typing.Optional[typing.Optional[str]] = Field(None, alias='issueNumber')

    owner_id: typing.Optional[typing.Optional[str]] = Field(None, alias='ownerId')

    security_code: typing.Optional[typing.Optional[str]] = Field(None, alias='securityCode')

    number: typing.Optional[typing.Optional[str]] = Field(None, alias='number')

    expiration_month: typing.Optional[int] = Field(None, alias='expirationMonth')

    expiration_year: typing.Optional[int] = Field(None, alias='expirationYear')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
